'use strict';

function renderAuthorIntelligenceMarkdown(dashboard) {
  const safeDashboard = dashboard || {};
  const summary = safeDashboard.summary || {};
  const lines = [];

  lines.push('# Author Intelligence Review Package');
  lines.push('');
  lines.push('## Overview');
  lines.push('');
  lines.push('- Generated: ' + safeInline(safeDashboard.generatedAt || 'unknown'));
  lines.push('- Status: ' + safeInline(safeDashboard.status || 'unknown'));
  lines.push('- Scope: ' + safeInline(scopeText(safeDashboard)));
  lines.push('- Report mode: ' + safeInline(safeDashboard.revisionMode || 'latest-per-thread'));
  lines.push('- Reports: ' + numeric(safeDashboard.reportCount) + ', revisions: ' + numeric(safeDashboard.reportRevisionCount));
  lines.push('- Threads: ' + numeric(summary.threadCount) + ', authors: ' + numeric(summary.authorCount) + ', opinions: ' + numeric(summary.opinionCount));
  lines.push('- Evidence gaps: ' + numeric(summary.evidenceGapCount) + ', review queue: ' + numeric(summary.reviewQueueCount));
  lines.push('- Review priority: ' + countSummary(summary.reviewQueuePriorityCounts));
  lines.push('- Review types: ' + countSummary(summary.reviewQueueTypeCounts));
  lines.push('- Recommended next action: ' + safeInline(safeDashboard.recommendedNextAction || safeDashboard.message || 'none'));

  lines.push('');
  lines.push('## Review Queue');
  lines.push('');
  appendReviewQueue(lines, safeDashboard.reviewQueue || []);

  lines.push('');
  lines.push('## Top Authors');
  lines.push('');
  appendAuthors(lines, safeDashboard.authors || []);

  lines.push('');
  lines.push('## Focus Entities');
  lines.push('');
  appendFocusEntities(lines, safeDashboard.focusEntities || []);

  lines.push('');
  lines.push('## Opinion Timeline');
  lines.push('');
  appendOpinionTimeline(lines, safeDashboard.opinionTimeline || []);

  lines.push('');
  lines.push('## Evidence Gaps');
  lines.push('');
  appendEvidenceGaps(lines, safeDashboard.evidenceGaps || []);

  lines.push('');
  lines.push('> Generated by ThreadTrace author intelligence. Use refs to verify source floors before downstream decisions.');
  lines.push('');

  return lines.join('\n');
}

function appendReviewQueue(lines, items) {
  if (items.length === 0) {
    lines.push('No review queue items.');
    return;
  }
  items.slice(0, 30).forEach(function (item, index) {
    lines.push((index + 1) + '. [' + safeInline(item.priority || 'unknown') + '] ' + safeInline(item.title || item.key || 'review item'));
    lines.push('   - Type: ' + safeInline(item.type || 'unknown') + ', score: ' + numeric(item.score) + ', reason: ' + safeInline(item.reason || 'unknown'));
    if (item.summary) {
      lines.push('   - Summary: ' + safeInline(item.summary));
    }
    if (item.nextAction) {
      lines.push('   - Next action: ' + safeInline(item.nextAction));
    }
    lines.push('   - Refs: ' + refsText(item.refs || []));
  });
}

function appendAuthors(lines, authors) {
  if (authors.length === 0) {
    lines.push('No author intelligence rows.');
    return;
  }
  authors.slice(0, 20).forEach(function (item) {
    const author = item.author || {};
    const intelligence = item.intelligence || {};
    lines.push('- ' + safeInline(displayAuthor(author)) +
      ': posts=' + numeric(item.postCount) +
      ', opinions=' + numeric(item.opinionCount) +
      ', threads=' + numeric(item.threadCount) +
      ', stance=' + safeInline(item.dominantStance || 'unknown') +
      ', latest=' + safeInline(item.latestAttitude || 'unknown') +
      ', confidence=' + confidenceText(item.averageOpinionConfidence) +
      ', evidence=' + safeInline(intelligence.evidenceStatus || 'unknown'));
    if (intelligence.summary) {
      lines.push('  - ' + safeInline(intelligence.summary));
    }
    if (item.topFocusEntities && item.topFocusEntities.length > 0) {
      lines.push('  - Focus: ' + item.topFocusEntities.slice(0, 5).map(function (entity) {
        return safeInline(displayEntity(entity.entity, entity.key)) + '/' + safeInline(entity.latestAttitude || 'unknown');
      }).join(', '));
    }
  });
}

function appendFocusEntities(lines, entities) {
  if (entities.length === 0) {
    lines.push('No focus entities.');
    return;
  }
  entities.slice(0, 20).forEach(function (item) {
    const levels = item.evidenceLevels || {};
    lines.push('- ' + safeInline(displayEntity(item.entity, item.key)) +
      ': mentions=' + numeric(item.mentionCount) +
      ', authorOpinions=' + numeric(item.primaryAuthorOpinionCount) +
      ', threads=' + numeric(item.threadCount) +
      ', latest=' + safeInline(item.latestAttitude || 'unknown') +
      ', explicit=' + numeric(levels.explicit) +
      ', inferred=' + numeric(levels.inferred));
  });
}

function appendOpinionTimeline(lines, items) {
  if (items.length === 0) {
    lines.push('No opinion timeline items.');
    return;
  }
  items.slice(0, 30).forEach(function (item) {
    const thread = item.thread || {};
    lines.push('- ' + refText({
      sourceKey: thread.sourceKey,
      sourceThreadId: thread.sourceThreadId,
      floor: item.floor,
      sourcePostId: item.sourcePostId
    }) +
      ' ' + safeInline(displayAuthor(item.author)) +
      ': attitude=' + safeInline(item.attitude || 'unknown') +
      ', confidence=' + confidenceText(item.confidence) +
      ', scope=' + safeInline(item.scope || 'unknown'));
    if (item.evidenceText) {
      lines.push('  - Evidence: ' + safeInline(item.evidenceText));
    }
  });
}

function appendEvidenceGaps(lines, gaps) {
  if (gaps.length === 0) {
    lines.push('No evidence gaps.');
    return;
  }
  gaps.slice(0, 30).forEach(function (gap) {
    lines.push('- ' + safeInline(displayEntity(gap.entity, gap.key)) +
      ': floors #' + safeInline(gap.firstFloor) + '-#' + safeInline(gap.lastFloor) +
      ', reason=' + safeInline(gap.reason || 'unknown') +
      ', thread=' + safeInline(gap.thread && gap.thread.sourceThreadId || 'unknown'));
    if (gap.summary) {
      lines.push('  - ' + safeInline(gap.summary));
    }
  });
}

function scopeText(dashboard) {
  const filter = dashboard.authorFilter || {};
  return [
    dashboard.sourceKey || 'all-sources',
    dashboard.sourceThreadId ? 'thread=' + dashboard.sourceThreadId : undefined,
    filter.authorId || filter.displayName ? 'author=' + (filter.displayName || filter.authorId) : undefined
  ].filter(Boolean).join(' / ');
}

function refsText(refs) {
  if (!refs || refs.length === 0) return 'none';
  return refs.slice(0, 6).map(refText).join(', ');
}

function refText(ref) {
  const safeRef = ref || {};
  return [
    safeRef.sourceKey || 'unknown-source',
    safeRef.sourceThreadId || 'unknown-thread'
  ].join('/') + (safeRef.floor === undefined || safeRef.floor === null ? '' : '#' + safeRef.floor);
}

function displayAuthor(author) {
  return author && (author.displayName || author.sourceAuthorId) || 'unknown-author';
}

function displayEntity(entity, fallback) {
  return entity && (entity.displayName || entity.normalized) || fallback || 'unknown-entity';
}

function confidenceText(value) {
  return value === undefined || value === null ? 'n/a' : String(value);
}

function countSummary(summary) {
  const keys = Object.keys(summary || {});
  if (keys.length === 0) return 'none';
  return keys.sort().map(function (key) {
    return key + '=' + summary[key];
  }).join(', ');
}

function safeInline(value) {
  return String(value === undefined || value === null ? '' : value).replace(/\s+/g, ' ').trim();
}

function numeric(value) {
  return typeof value === 'number' && Number.isFinite(value) ? value : 0;
}

module.exports = {
  renderAuthorIntelligenceMarkdown
};
